function loginUI() {
	return '<div class="je_sign-in-form" >'
    +'<h1 class="je_sign-in-form__header">'
    +'<a id="main_btn" class="je_sign-in-form__header__link" href="#">'
      +'<span style=" margin-left: auto; margin-right: auto;  display: block;">'
<<<<<<< HEAD
    + ' <img class="je_manImg" src='+$.img()+'/logo1.png ></img></span>'
+'</a>    </h1>'
+'<form class="je_sign-in-form__form" id="new_user">'
  +'<input placeholder="이메일" autofocus="autofocus" class="je_sign-in-form__form__input form-control sign-in-form__form__email" type="text" name="user[email]" id="user_email">'
  +'<div class="je_sign-in-form__form__input-wrap je_sign-in-form__form__password">'
    +'<input placeholder="비밀번호" autocomplete="off" class="je_sign-in-form__form__input form-control" type="password" name="user[password]" id="user_password">'
  +'</div>'
  +'<input type="hidden" name="remember_me" id="remember_me" value="checked">'
  +'<input type="hidden" name="is_pro" id="is_pro" value="false">'
  +'<input id="login_btn1" type="button" name="commit" value="로그인" class="je_sign-in-form__form__submit btn je_btn-priority" data-disable-with="로그인">'
+'</form>    <div class="je_sign-in-form__action">'
    +'<a class="je_sign-in-form__action__entry" href="/users/password/new">비밀번호 재설정</a>'
    +'<a id="join_btn1" class="je_sign-in-form__action__entry" href="#">회원가입</a>'
+'</div>'
  +'<section class="je_sign-in-form__sns">'
    +'<div class="je_sign-in-form__sns__list">'
    +'<p style="font-size:80%; color:gray;">SNS계정으로 간편 로그인/회원가입</p>'
	+'<img class="manImg" src='+$.img()+'/kakao.png ></img></a>&nbsp&nbsp&nbsp'
	+'<img class="manImg" src='+$.img()+'/naver.png ></img></a>'
=======
    + ' <img class="je_manImg" src='+$.img()+'/jieun/logo1.png ></img></span>'
+'</a>    </h1>'
+'<form class="je_sign-in-form__form" id="new_user">'
  +'<input placeholder="이메일" autofocus="autofocus" class="je_sign-in-form__form__input form-control sign-in-form__form__email" type="text" name="user[email]" id="user_email">'
  +'<div class="je_sign-in-form__form__input-wrap je_sign-in-form__form__password">'
    +'<input placeholder="비밀번호" autocomplete="off" class="je_sign-in-form__form__input form-control" type="password" name="user[password]" id="user_password">'
  +'</div>'
  +'<input type="hidden" name="remember_me" id="remember_me" value="checked">'
  +'<input type="hidden" name="is_pro" id="is_pro" value="false">'
  +'<input id="login_btn1" type="button" name="commit" value="로그인" class="je_sign-in-form__form__submit btn je_btn-priority" data-disable-with="로그인">'
+'</form>    <div class="je_sign-in-form__action">'
    +'<a class="je_sign-in-form__action__entry" href="/users/password/new">비밀번호 재설정</a>'
    +'<a id="join_btn1" class="je_sign-in-form__action__entry" href="#">회원가입</a>'
+'</div>'
  +'<section class="je_sign-in-form__sns">'
    +'<div class="je_sign-in-form__sns__list">'
    +'<p style="font-size:80%; color:gray;">SNS계정으로 간편 로그인/회원가입</p>'
	+'<img class="manImg" src='+$.img()+'/jieun/kakao.png ></img></a>&nbsp&nbsp&nbsp'
	+'<img class="manImg" src='+$.img()+'/jieun/naver.png ></img></a>'
>>>>>>> refs/remotes/origin/master
+'       <a class="je_sign-in-form__sns__entry" href="/users/auth/kakao">'
        +'<span class="icon-page-login__c-3" aria-label="카카오계정으로 로그인"></span>'
+'</a>          <a class="je_sign-in-form__sns__entry" href="/users/auth/naver">'
        +'<span class="icon-page-login__e-3" aria-label="네이버 아이디로 로그인"></span>'
+'</a>        </div>'
  +'</section>'
+'</div>';
}