function navUI() {
	return '<div id="navigation">'
	+'<nav class="navigation-primary-wrap sticky-top" style="height: 81px;">'
    +'<div class="navigation-primary__container sticky-content float open" style="position: fixed; bottom: auto; top: 0px;">'
    +'<div class="navigation-primary">'
      +'<button class="navigation-primary__menu-btn" aria-label="메뉴 열기">'
        +'<span class="icon icon-etc-button-hamburger"></span>'
      +'</button>'
      +'<a class="navigation-primary__logo" href="/">'
      +'<span id="main_logo_btn" style="padding-right:3px; padding-top: 3px; display:inline-block;">'
      + ' <img class="manImg" src='+$.img()+'/logo.png ></img></span>'
+'</a>        <div class="navigation-primary__menu open">'
        +'<ul id="nav_ul" class="navigation-menu">'
+'<li class="navigation-menu__primary current active">'
  +'<div class="title">'
    +'<a id="board_btn" href="#">'
      +'커뮤니티'
+'</a>    </div>'
+'</li>'
+'<li class="navigation-menu__primary">'
  +'<div class="title">'
    +'<a href="/store">'
      +'<span class="icon mobile-icon icon-shortcut-store"></span>'
      +'스토어'
      +'<span class="open-btn">'
        +'<span class="icon mobile-icon icon-pointer-angle-down-dark-md"></span>'
      +'</span>'
+'</a>    </div>'
+'</li>'
+'<li class="navigation-menu__primary">'
  +'<div class="title">'
    +'<a href="/experts">'
      +'<span class="icon mobile-icon icon-shortcut-expert"></span>'
      +'통계'
      +'<span class="open-btn">'
        +'<span class="icon mobile-icon icon-pointer-angle-down-dark-md"></span>'
      +'</span>'
+'</a>    </div>'
+'</li>'
+'</ul>'
      +'</div>'
      +'<div class="navigation-primary__search">'
        +'<form class="navigation-search" action="#" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">'
+'<div class="navigation-search__box" data-type="">'
  +'<input class="navigation-search__box__submit" type="submit">'
  +'<button class="navigation-search__box__icon" type="button">'
    +'<span class="icon icon-etc-find-md-gray-dark"></span>'
    +'<span class="icon icon-pointer-triangle-down-gray-dark-xs caret"></span>'
  +'</button>'
  +'<span class="navigation-search__box__icon_blur">'
    +'<span class="icon icon-etc-find-md-gray-dark"></span>'
  +'</span>'
+'</div>'
+'<div style="display: none;"></div></form>'
      +'</div>'
      +'<div class="navigation-primary__actions">'
          +'<span class="icon icon-etc-find-md-gray-dark"></span>'
          +'<span class="icon active icon-etc-find-md-white"></span>'
        +'</button>'
          +'<span class="icon icon-etc-cart-gray"></span>'
          +'<span class="icon active icon-etc-cart-white"></span>'
+'</a>          <a class="navigation-primary__cart-btn navigation-primary__button button-sm-only" title="장바구니" href="/shoppingMobileCart">'
          +'<span class="icon icon-etc-cart-gray"></span>'
          +'<span class="icon active icon-etc-cart-white"></span>'
+'</a>        </div>'
        +'<div class="navigation-primary__user unlogged">'
          +'<div id="li_id" class="navigation-primary__user__unlogged">'
            +'<a id="login_btn" class="navigation-primary__user__unlogged__login" href="#">로그인</a>'
            +'<a id="join_btn" class="navigation-primary__user__unlogged__register" href="#">회원가입</a>'
          +'</div>'
        +'</div>'
    +'</div>'
  +'</div>'
+'</nav></div>';
}