INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '[무료배송/최저가] 무노 베드테이블 2size', '20,30',11, 46);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( 'BEEDN 비드앤 엠보 가죽 패밀리 침대 5종 (저상형) 3color', '20,30',12, 46);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '미휴 수납헤드 수납형 슈퍼싱글 침대 3colors', '20,400',13, 46);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '[카페 패브릭 접이식 소파베드 3colors', '10,20',14, 47);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '플랫베드 침대 / 롤링매트리스', '40,10',15, 47);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '화이트&블랙 선반행거/5단선반', '10,20',16, 47);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '간편조립 모듈수납함 선반장 5종 4colors', '300,200',17, 47);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '미샤 전신거울 옷장/장롱 3colors', '200,10',18, 48);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '무드갤러리 장롱 옷장 2colors', '20,400',19, 48);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( 'MKB 캐비넷 옷장 5colors 7601690', '200,10',20, 48);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( 'FILMON 수납장 2colors', '20,30',21, 48);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '무노 현관 파티션 신발장 수납장 3colors', '40,10',22, 49);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '테미스 와이드 거실 수납장 3sizes', '300,200',23, 49);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '바스페이스 3단 문걸이 수납장', '40,10',24, 49);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '에르미 화장대 2colors', '10,20',26, 49);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '[무료배송/최저가] 무노 베드테이블 2size', '20,400',11, 50);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( 'BEEDN 비드앤 엠보 가죽 패밀리 침대 5종 (저상형) 3color', '20,30',12, 50);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '미휴 수납헤드 수납형 슈퍼싱글 침대 3colors', '20,400',13, 50);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '[카페 패브릭 접이식 소파베드 3colors', '200,10',14, 50);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '플랫베드 침대 / 롤링매트리스', '300,200',15, 51);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '화이트&블랙 선반행거/5단선반', '10,20',16, 51);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '간편조립 모듈수납함 선반장 5종 4colors', '300,200',17, 51);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '미샤 전신거울 옷장/장롱 3colors', '40,10',18, 51);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '무드갤러리 장롱 옷장 2colors', '20,30',19, 52);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( 'MKB 캐비넷 옷장 5colors 7601690', '20,30',20, 52);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( 'FILMON 수납장 2colors', '20,400',21, 52);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '무노 현관 파티션 신발장 수납장 3colors', '10,20',22, 53);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '테미스 와이드 거실 수납장 3sizes', '10,20',23, 53);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '바스페이스 3단 문걸이 수납장', '300,200',24, 53);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '에르미 화장대 2colors', '200,10',26, 54);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '쿠엔코 높은 주방 수납장 8종', '40,10',35, 54);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '카트트롤리/수납장/스틸수납장(DIY) 2colors', '20,30',36, 54);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '아이나 다용도 수납장 A', '40,10',37, 55);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '제이스 LED 침대 슈퍼싱글(SS)/퀸(Q) 2colors', '20,400',38, 55);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '멀티 트윈/멀티침대 소파베드', '20,400',39, 56);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '미니멀 평상형 침대/수납침대 모음전', '300,200',40, 57);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '아이나 벤치형 침대 (1900조명형)', '20,30',41, 58);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '네이쳐 원목 통다리 책상 겸 테이블 5size', '10,20',42, 59);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '브루노 스타일 책상 4size 2colors', '200,10',43, 60);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '쿠엔코 높은 주방 수납장 8종', '200,10',35, 65);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '카트트롤리/수납장/스틸수납장(DIY) 2colors', '200,10',36, 66);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '아이나 다용도 수납장 A', '300,200',37, 66);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '제이스 LED 침대 슈퍼싱글(SS)/퀸(Q) 2colors', '40,10',38, 66);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '멀티 트윈/멀티침대 소파베드', '10,20',39, 77);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '미니멀 평상형 침대/수납침대 모음전', '200,10',40, 78);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '아이나 벤치형 침대 (1900조명형)', '40,10',41, 79);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '네이쳐 원목 통다리 책상 겸 테이블 5size', '20,400',42, 80);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '브루노 스타일 책상 4size 2colors', '300,200',43, 81);
INSERT INTO mariadb.imgtag (ITEM_TITLE, POINT, ITEM_SEQ, POST_SEQ) VALUES( '무드갤러리 장롱 옷장 2colors', '300,200',19, 82);